
services:
  - name: nodejs
    env:
      - key: PORT
        value: "8000"
      - key: MONGODB_URI
        from_secret: MONGODB_URI  # Reference the secret by name
      - key: EMAIL_USER
        from_secret: EMAIL_USER
      - key: EMAIL_PASS
        from_secret: EMAIL_PASS
    build_command: npm install
    start_command: npm start
